<#
.SYNOPSIS
Executes VMware to Hyper-V migration from PRE manifest.

.DESCRIPTION
Consumes manifest-<VMName>.json generated by PRE phase, exports/copies VMDKs,
converts them to VHDX, creates Hyper-V VM, optionally starts the VM, and updates
manifest with exec_result.

.PARAMETER VMName
Virtual machine name.

.PARAMETER ManifestPath
Path to migration manifest JSON file.

.PARAMETER HyperVHost
Destination Hyper-V host.

.PARAMETER VMStoragePath
Hyper-V VM configuration path.

.PARAMETER VHDXPath
Destination folder for generated VHDX files.

.PARAMETER SwitchName
Hyper-V virtual switch name.

.PARAMETER ConversionTool
VMDK to VHDX conversion tool.

.PARAMETER StartVMAfterMigration
Start VM after creation.

.PARAMETER ShutdownSourceVM
Attempt graceful source VM shutdown before export.

.EXAMPLE
.\02-EXEC-Migration.ps1 -VMName "SRVWEB01" -ManifestPath "C:\Migration\Manifests\manifest-SRVWEB01.json"

.NOTES
Version: 1.0.0
Author: GitHub Copilot
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$VMName,
    [string]$ManifestPath = "C:\Migration\Manifests\manifest-$VMName.json",
    [string]$HyperVHost = $env:HYPERV_HOST,
    [string]$VMStoragePath = $env:HYPERV_VM_PATH,
    [string]$VHDXPath = $env:HYPERV_VHDX_PATH,
    [string]$SwitchName = $env:HYPERV_SWITCH,
    [ValidateSet('StarWindV2V', 'MVMC', 'QemuImg')][string]$ConversionTool = 'StarWindV2V',
    [switch]$StartVMAfterMigration,
    [switch]$ShutdownSourceVM
)

Set-StrictMode -Version 2.0
$script:PhaseName = 'PHASE-EXEC'

function Write-MigLog {
    param(
        [Parameter(Mandatory)][ValidateSet('INFO', 'WARN', 'ERROR', 'FATAL')][string]$Level,
        [Parameter(Mandatory)][string]$Message
    )
    Write-Output "[$(Get-Date -Format 'yyyy-MM-ddTHH:mm:ss')][$Level][$script:PhaseName] $Message"
}

function Get-StarWindExe {
    $candidates = @(
        'StarWindV2VConverter.exe',
        'C:\Program Files\StarWind Software\StarWind V2V Converter\StarWindV2VConverter.exe',
        'C:\Program Files\StarWind\StarWind V2V Converter\StarWindV2VConverter.exe'
    )
    foreach ($c in $candidates) {
        $cmd = Get-Command -Name $c -ErrorAction SilentlyContinue
        if ($cmd) { return $cmd.Source }
        if (Test-Path -Path $c) { return $c }
    }
    return $null
}

function Invoke-Conversion {
    param(
        [Parameter(Mandatory)][string]$Source,
        [Parameter(Mandatory)][string]$Destination,
        [Parameter(Mandatory)][ValidateSet('StarWindV2V', 'MVMC', 'QemuImg')][string]$Tool,
        [Parameter(Mandatory)][string]$LogPath
    )

    switch ($Tool) {
        'StarWindV2V' {
            $exe = Get-StarWindExe
            if (-not $exe) {
                throw 'StarWind V2V Converter executable not found.'
            }
            $args = @(
                '/source', $Source,
                '/dest', $Destination,
                '/format', 'vhdx',
                '/type', 'dynamic'
            )
            $output = & $exe $args 2>&1
            $output | Out-File -FilePath $LogPath -Encoding UTF8
        }
        'MVMC' {
            if (-not (Get-Command -Name ConvertTo-MvmcVirtualHardDisk -ErrorAction SilentlyContinue)) {
                throw 'ConvertTo-MvmcVirtualHardDisk command is not available.'
            }
            $output = ConvertTo-MvmcVirtualHardDisk -SourceLiteralPath $Source -VhdType DynamicHardDisk -VhdFormat Vhdx -DestinationLiteralPath $Destination 2>&1
            $output | Out-File -FilePath $LogPath -Encoding UTF8
        }
        'QemuImg' {
            $qemu = Get-Command -Name 'qemu-img.exe' -ErrorAction SilentlyContinue
            if (-not $qemu) {
                throw 'qemu-img.exe is not available in PATH.'
            }
            $args = @('convert', '-f', 'vmdk', '-O', 'vhdx', $Source, $Destination)
            $output = & $qemu.Source $args 2>&1
            $output | Out-File -FilePath $LogPath -Encoding UTF8
        }
    }

    if (-not (Test-Path -Path $Destination)) {
        throw "Converted VHDX not found at destination: $Destination"
    }
    $file = Get-Item -Path $Destination
    if ($file.Length -le 0) {
        throw "Converted VHDX is empty: $Destination"
    }
}

$execStatus = 'SUCCESS'
$conversionFailures = 0
$conversionFiles = New-Object System.Collections.Generic.List[object]
$migrationSnapshotName = $null
$stepTimers = @{}

try {
    #region ÉTAPE 1 — Validation du manifest
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    if (-not (Test-Path -Path $ManifestPath)) {
        Write-MigLog -Level FATAL -Message "Manifest not found: $ManifestPath"
        exit 2
    }

    $manifest = Get-Content -Path $ManifestPath -Raw | ConvertFrom-Json
    if ($manifest.overall_status -eq 'BLOCKED') {
        Write-MigLog -Level FATAL -Message 'Manifest status is BLOCKED. Execution aborted.'
        exit 2
    }

    $schemaVersion = [version]($manifest.schema_version)
    if ($schemaVersion -lt [version]'1.0') {
        Write-MigLog -Level FATAL -Message "Unsupported manifest schema version: $($manifest.schema_version)"
        exit 2
    }

    if (-not $HyperVHost -or -not $VMStoragePath -or -not $VHDXPath -or -not $SwitchName) {
        Write-MigLog -Level FATAL -Message 'Hyper-V target settings are incomplete (host/path/switch).'
        exit 3
    }

    if (-not (Test-Path -Path $VMStoragePath)) { New-Item -Path $VMStoragePath -ItemType Directory -Force | Out-Null }
    if (-not (Test-Path -Path $VHDXPath)) { New-Item -Path $VHDXPath -ItemType Directory -Force | Out-Null }
    $tempRoot = Join-Path -Path $env:TEMP -ChildPath ("Migration\$VMName")
    if (-not (Test-Path -Path $tempRoot)) { New-Item -Path $tempRoot -ItemType Directory -Force | Out-Null }

    $sw.Stop()
    $stepTimers['validate_manifest_s'] = [Math]::Round($sw.Elapsed.TotalSeconds, 2)
    #endregion

    #region ÉTAPE 2 — Arrêt de la VM source
    if ($ShutdownSourceVM) {
        $sw = [System.Diagnostics.Stopwatch]::StartNew()
        try {
            $sourceVm = Get-VM -Name $VMName -ErrorAction Stop
            Write-MigLog -Level INFO -Message "Source VM power state before shutdown: $($sourceVm.PowerState)"

            if ($sourceVm.PowerState -ne 'PoweredOff') {
                Shutdown-VMGuest -VM $sourceVm -Confirm:$false -ErrorAction SilentlyContinue | Out-Null
                $timeout = (Get-Date).AddMinutes(5)
                do {
                    Start-Sleep -Seconds 10
                    $sourceVm = Get-VM -Name $VMName -ErrorAction SilentlyContinue
                    Write-Progress -Activity 'Shutting down source VM' -Status "Current state: $($sourceVm.PowerState)"
                } while ($sourceVm -and $sourceVm.PowerState -ne 'PoweredOff' -and (Get-Date) -lt $timeout)

                if ($sourceVm.PowerState -ne 'PoweredOff') {
                    Write-MigLog -Level WARN -Message 'Graceful shutdown timed out. Forcing stop.'
                    Stop-VM -VM $sourceVm -Kill -Confirm:$false -ErrorAction SilentlyContinue | Out-Null
                }
            }

            $sourceVm = Get-VM -Name $VMName -ErrorAction Stop
            Write-MigLog -Level INFO -Message "Source VM power state after shutdown flow: $($sourceVm.PowerState)"
        }
        catch {
            Write-MigLog -Level ERROR -Message "Source shutdown step failed: $($_.Exception.Message)"
            Write-MigLog -Level ERROR -Message "$($_.ScriptStackTrace)"
        }
        $sw.Stop()
        $stepTimers['shutdown_source_s'] = [Math]::Round($sw.Elapsed.TotalSeconds, 2)
    }
    #endregion

    #region ÉTAPE 3 — Export/préparation VMDK
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    $sourceVmForExport = Get-VM -Name $VMName -ErrorAction Stop
    $isWarm = $sourceVmForExport.PowerState -ne 'PoweredOff'
    $copiedVmdks = New-Object System.Collections.Generic.List[object]

    if ($isWarm) {
        $migrationSnapshotName = "MIG-EXPORT-$($manifest.migration_id)"
        Write-MigLog -Level INFO -Message "Creating temporary snapshot: $migrationSnapshotName"
        New-Snapshot -VM $sourceVmForExport -Name $migrationSnapshotName -Description 'Temporary snapshot for migration export' -Quiesce:$false -Memory:$false -ErrorAction Stop | Out-Null
    }

    try {
        $totalDisks = @($manifest.disks).Count
        $diskIndex = 0
        foreach ($disk in $manifest.disks) {
            $diskIndex++
            $srcPath = [string]$disk.vmdk_path
            $leaf = Split-Path -Path $srcPath -Leaf
            $destPath = Join-Path -Path $tempRoot -ChildPath $leaf

            $pct = [int](($diskIndex / [Math]::Max($totalDisks, 1)) * 100)
            Write-Progress -Activity 'Copying VMDK files' -Status "$leaf ($diskIndex/$totalDisks)" -PercentComplete $pct

            if (Test-Path -Path $srcPath) {
                Copy-Item -Path $srcPath -Destination $destPath -Force -ErrorAction Stop
            }
            else {
                Write-MigLog -Level WARN -Message "Source VMDK path not directly accessible from worker: $srcPath"
                # Keep path for external copy mechanisms; fallback to manifest path as-is.
                $destPath = $srcPath
            }

            $copiedVmdks.Add([pscustomobject]@{
                label = $disk.label
                source = $srcPath
                local_copy = $destPath
            }) | Out-Null
        }
    }
    finally {
        if ($isWarm -and $migrationSnapshotName) {
            try {
                $snap = Get-Snapshot -VM $sourceVmForExport -Name $migrationSnapshotName -ErrorAction SilentlyContinue
                if ($snap) {
                    Remove-Snapshot -Snapshot $snap -Confirm:$false -RunAsync:$false -ErrorAction Stop | Out-Null
                    Write-MigLog -Level INFO -Message "Temporary snapshot removed: $migrationSnapshotName"
                }
            }
            catch {
                Write-MigLog -Level WARN -Message "Could not remove temporary snapshot ${migrationSnapshotName}: $($_.Exception.Message)"
            }
        }
    }

    $sw.Stop()
    $stepTimers['export_prepare_s'] = [Math]::Round($sw.Elapsed.TotalSeconds, 2)
    #endregion

    #region ÉTAPE 4 — Conversion VMDK -> VHDX
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    $diskTotal = $copiedVmdks.Count
    $diskCurrent = 0

    foreach ($disk in $copiedVmdks) {
        $diskCurrent++
        $labelSafe = ([string]$disk.label) -replace '[^a-zA-Z0-9\-_]', '_'
        if ([string]::IsNullOrWhiteSpace($labelSafe)) { $labelSafe = "disk$diskCurrent" }

        $destVhdx = Join-Path -Path $VHDXPath -ChildPath ("{0}-{1}.vhdx" -f $VMName, $labelSafe)
        $convLog = Join-Path -Path $VHDXPath -ChildPath ("conversion-{0}-{1}.log" -f $VMName, $labelSafe)

        $pct = [int](($diskCurrent / [Math]::Max($diskTotal, 1)) * 100)
        Write-Progress -Activity 'Converting VMDK to VHDX' -Status "$($disk.label) ($diskCurrent/$diskTotal)" -PercentComplete $pct

        try {
            Invoke-Conversion -Source $disk.local_copy -Destination $destVhdx -Tool $ConversionTool -LogPath $convLog
            $vhdxInfo = Get-Item -Path $destVhdx
            $conversionFiles.Add([pscustomobject]@{
                label = $disk.label
                path = $destVhdx
                size_gb = [Math]::Round(($vhdxInfo.Length / 1GB), 2)
                conversion_tool = $ConversionTool
            }) | Out-Null
            Write-MigLog -Level INFO -Message "Converted disk '$($disk.label)' successfully to $destVhdx"
        }
        catch {
            $conversionFailures++
            $execStatus = 'PARTIAL'
            Write-MigLog -Level ERROR -Message "Conversion failed for disk '$($disk.label)': $($_.Exception.Message)"
            Write-MigLog -Level ERROR -Message "$($_.ScriptStackTrace)"
        }
    }

    if ($conversionFiles.Count -eq 0) {
        Write-MigLog -Level FATAL -Message 'No disk was successfully converted.'
        exit 4
    }

    $sw.Stop()
    $conversionDurationSec = [Math]::Round($sw.Elapsed.TotalSeconds, 2)
    $stepTimers['conversion_s'] = $conversionDurationSec
    #endregion

    #region ÉTAPE 5 — Création VM Hyper-V
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    $generation = if ($manifest.compute.firmware -eq 'efi') { 2 } else { 1 }

    try {
        $existingHyperV = Get-VM -Name $VMName -ComputerName $HyperVHost -ErrorAction SilentlyContinue
        if ($existingHyperV) {
            Write-MigLog -Level WARN -Message "Hyper-V VM already exists, removing before recreate: $VMName"
            if ($existingHyperV.State -eq 'Running') {
                Stop-VM -Name $VMName -ComputerName $HyperVHost -TurnOff -Force -ErrorAction SilentlyContinue
            }
            Remove-VM -Name $VMName -ComputerName $HyperVHost -Force -ErrorAction Stop
        }

        New-VM -Name $VMName -ComputerName $HyperVHost -MemoryStartupBytes ([int]$manifest.compute.ram_mb * 1MB) -Generation $generation -Path $VMStoragePath -ErrorAction Stop | Out-Null

        if (($generation -eq 2) -and (-not [bool]$manifest.compute.secure_boot)) {
            Set-VMFirmware -VMName $VMName -ComputerName $HyperVHost -EnableSecureBoot Off -ErrorAction Stop
        }

        Set-VMProcessor -VMName $VMName -ComputerName $HyperVHost -Count ([int]$manifest.compute.vcpu) -ErrorAction Stop

        $location = 0
        foreach ($v in $conversionFiles) {
            Add-VMHardDiskDrive -VMName $VMName -ComputerName $HyperVHost -ControllerType SCSI -ControllerNumber 0 -ControllerLocation $location -Path $v.path -ErrorAction Stop | Out-Null
            $location++
        }

        $createdNics = New-Object System.Collections.Generic.List[string]
        foreach ($nic in $manifest.network_adapters) {
            $adapterName = [string]$nic.name
            if ([string]::IsNullOrWhiteSpace($adapterName)) {
                $adapterName = "NIC$($createdNics.Count + 1)"
            }

            Add-VMNetworkAdapter -VMName $VMName -ComputerName $HyperVHost -SwitchName $SwitchName -Name $adapterName -ErrorAction Stop | Out-Null
            if ($nic.mac) {
                $mac = ([string]$nic.mac).Replace(':', '').Replace('-', '')
                Set-VMNetworkAdapter -VMName $VMName -ComputerName $HyperVHost -Name $adapterName -StaticMacAddress $mac -ErrorAction SilentlyContinue | Out-Null
            }
            $createdNics.Add($adapterName) | Out-Null
        }

        if ($generation -eq 2) {
            $hdds = Get-VMHardDiskDrive -VMName $VMName -ComputerName $HyperVHost | Sort-Object ControllerLocation
            $nics = Get-VMNetworkAdapter -VMName $VMName -ComputerName $HyperVHost
            if ($hdds.Count -gt 0) {
                $bootOrder = @($hdds[0]) + @($nics)
                Set-VMFirmware -VMName $VMName -ComputerName $HyperVHost -BootOrder $bootOrder -ErrorAction SilentlyContinue | Out-Null
            }
        }

        Set-VM -Name $VMName -ComputerName $HyperVHost -AutomaticStopAction ShutDown -AutomaticStartAction Nothing -ErrorAction Stop | Out-Null

        if ($StartVMAfterMigration) {
            Start-VM -Name $VMName -ComputerName $HyperVHost -ErrorAction Stop | Out-Null
        }
    }
    catch {
        Write-MigLog -Level FATAL -Message "Hyper-V VM creation failed: $($_.Exception.Message)"
        Write-MigLog -Level ERROR -Message "$($_.ScriptStackTrace)"
        exit 5
    }

    $sw.Stop()
    $stepTimers['create_vm_s'] = [Math]::Round($sw.Elapsed.TotalSeconds, 2)
    #endregion

    #region ÉTAPE 6 — Injection drivers Hyper-V (optionnelle)
    $driverInjectionStatus = 'skipped'
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    try {
        if (($manifest.compute.firmware -eq 'efi') -and ($manifest.source.os_guest -match 'Windows') -and ($conversionFiles.Count -gt 0)) {
            $systemDisk = $conversionFiles[0].path
            Write-MigLog -Level INFO -Message "Attempting driver injection on disk: $systemDisk"
            $mounted = Mount-VHD -Path $systemDisk -Passthru -ErrorAction Stop
            try {
                $disk = $mounted | Get-Disk -ErrorAction Stop
                $partitions = $disk | Get-Partition -ErrorAction Stop
                $windowsPartition = $partitions | Sort-Object Size -Descending | Select-Object -First 1
                $vol = $windowsPartition | Get-Volume -ErrorAction Stop
                $driveLetter = $vol.DriveLetter

                if ($driveLetter) {
                    $windowsPath = "${driveLetter}:\Windows"
                    if (Test-Path -Path $windowsPath) {
                        $dismArgs = @(
                            '/Image:' + "${driveLetter}:\",
                            '/Add-Driver',
                            '/Driver:C:\Windows\System32\drivers',
                            '/Recurse'
                        )
                        $dismOutput = & dism.exe $dismArgs 2>&1
                        $dismOutput | Out-File -FilePath (Join-Path -Path $VHDXPath -ChildPath "dism-$VMName.log") -Encoding UTF8
                        $driverInjectionStatus = 'success'
                    }
                    else {
                        $driverInjectionStatus = 'failed'
                        Write-MigLog -Level WARN -Message 'Injected disk does not contain expected Windows folder.'
                    }
                }
                else {
                    $driverInjectionStatus = 'failed'
                    Write-MigLog -Level WARN -Message 'No drive letter assigned to mounted VHD.'
                }
            }
            finally {
                Dismount-VHD -Path $systemDisk -ErrorAction SilentlyContinue
            }
        }
    }
    catch {
        $driverInjectionStatus = 'failed'
        Write-MigLog -Level WARN -Message "Driver injection failed: $($_.Exception.Message)"
    }
    $sw.Stop()
    $stepTimers['driver_injection_s'] = [Math]::Round($sw.Elapsed.TotalSeconds, 2)
    #endregion

    #region ÉTAPE 7 — Mise à jour du manifest
    if ($conversionFailures -gt 0 -and $execStatus -eq 'SUCCESS') {
        $execStatus = 'PARTIAL'
    }

    $manifest | Add-Member -MemberType NoteProperty -Name exec_result -Value ([ordered]@{
        hyperv_vm_name = $VMName
        hyperv_host = $HyperVHost
        vhdx_files = @($conversionFiles)
        conversion_duration_seconds = $conversionDurationSec
        vm_created_at = (Get-Date).ToString('o')
        network_adapters_created = @($manifest.network_adapters | ForEach-Object { $_.name })
        driver_injection = $driverInjectionStatus
        migration_snapshot_name = $migrationSnapshotName
        exec_status = $execStatus
        step_timers = $stepTimers
    }) -Force

    $manifest | ConvertTo-Json -Depth 12 | Set-Content -Path $ManifestPath -Encoding UTF8
    Write-MigLog -Level INFO -Message "Manifest updated with exec_result: $ManifestPath"
    #endregion

    if ($execStatus -eq 'FAILED') {
        exit 5
    }

    if ($conversionFailures -gt 0) {
        Write-MigLog -Level WARN -Message "Execution completed partially: $conversionFailures conversion failure(s)."
    }
    else {
        Write-MigLog -Level INFO -Message 'Execution completed successfully.'
    }

    exit 0
}
catch {
    Write-MigLog -Level ERROR -Message "Unexpected error: $($_.Exception.Message)"
    Write-MigLog -Level ERROR -Message "$($_.ScriptStackTrace)"
    exit 1
}
